#!/bin/sh
# Conventional Commits header check.
#
# Usage: sh scripts/commit-msg.sh <commit-msg-file>
# Called by lefthook's commit-msg hook; "$1" is the file holding the message.
#
# Accepts:  <type>(<optional scope>)!: <description>
# Types:    feat fix docs style refactor perf test build ci chore revert
# Skips:    "Merge ..." and "Revert ..." headers (generated by git).

file="$1"

if [ -z "$file" ] || [ ! -f "$file" ]; then
  echo "commit-msg: no message file provided" >&2
  exit 1
fi

header="$(head -n 1 "$file")"

case "$header" in
  Merge\ *|Revert\ *)
    exit 0
    ;;
esac

pattern='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9._/-]+\))?!?: .+'

if ! printf '%s\n' "$header" | grep -Eq "$pattern"; then
  echo "Invalid commit message:" >&2
  echo "  $header" >&2
  echo >&2
  echo "Expected:" >&2
  echo "  <type>(<optional scope>): <description>" >&2
  echo >&2
  echo "Types: feat fix docs style refactor perf test build ci chore revert" >&2
  echo >&2
  echo "Examples:" >&2
  echo "  feat(parser): support nested input" >&2
  echo "  fix(nlp): avoid empty-token panic" >&2
  echo "  docs: update rule documentation" >&2
  exit 1
fi
